// The trailer's charge-up sound, played when the plug docks into the J.
// It is timed to the wordmark fill (clip-path over 2.35s on --ease-charge) and generated by the
// trailer project's sfx.mjs, so the click, the rising tone, and the bell land with the fill.
const SRC = "/sounds/charge.mp3";
const VOLUME = 0.5;
// A start later than this would trail the animation it accompanies, so it is skipped instead.
const MAX_START_DELAY_MS = 250;

let context: AudioContext | null = null;
let bytes: Promise<ArrayBuffer | null> | null = null;
let decoded: Promise<AudioBuffer | null> | null = null;

// Downloading needs no user gesture, so the file can arrive ahead of the first plug-in.
export function preloadChargeSound() {
  bytes ??= fetch(SRC)
    .then((response) => (response.ok ? response.arrayBuffer() : null))
    .catch(() => null);
}

// Browsers only allow audio after a user gesture, so the context is created on the first press.
export function primeChargeSound() {
  if (context || typeof window === "undefined") return;
  const AudioContextClass =
    window.AudioContext ?? (window as Window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!AudioContextClass) return;
  const created = new AudioContextClass();
  context = created;
  preloadChargeSound();
  decoded = bytes!.then((data) => (data ? created.decodeAudioData(data) : null)).catch(() => null);
}

export function playChargeSound() {
  primeChargeSound();
  const ctx = context;
  if (!ctx || !decoded) return;
  const requestedAt = performance.now();
  void ctx.resume().catch(() => undefined);
  void decoded.then((buffer) => {
    if (!buffer || performance.now() - requestedAt > MAX_START_DELAY_MS) return;
    const source = ctx.createBufferSource();
    const gain = ctx.createGain();
    source.buffer = buffer;
    gain.gain.value = VOLUME;
    source.connect(gain).connect(ctx.destination);
    source.start();
  });
}
